
export class CommonConstants {

  static readonly SEARCH_WEIGHT:number=10;

  static readonly DIVIDER_STROKE_WIDTH:number=1;

  static readonly DETAIL_LIST_OFFSET_LG:number=1

  static readonly DETAIK_LIST_OFFSET_MD:number=1

  static readonly DETAIL_LIST_SPAN_LG:number=9

  static readonly TAB_ITEM_FONT_WEIGHT: number = 500;

  static readonly FULL_WIDTH_PERCENT: string = '100%';
  static readonly FULL_HEIGHT_PERCENT: string = '100%';
}